### ISSUE TITLE
rgbled.begin();  が rbgled.begin();　になってしまうようです。

### ISSUE THREAD

**Issue by iwasa183** [okhiroyuki/BlocklyDuinoEditor#5]
いつもお世話になりありがとうございます。

NeoPixcelのLEDの初期設定をGRBからRGBに変更していただいた件ですが、件名の通り、rgbled.begin(); が rbgled.begin(); となってしまいエラーになります。
他の箇所は今まで試した範囲では　rgbled. となっているようです。

**Comment by okhiroyuki** [comment]
失礼しました。
修正いたします。

**Comment by iwasa183** [comment]
こちらこそ試すのが遅くなり申し訳ありません。どうぞ宜しくお願い致します。m(_ _)m

**Comment by iwasa183** [comment]
遅くなりましたが動作確認しました。ありがとうございました。

**Comment by okhiroyuki** [comment]
よかったです。
こちらこそ、対応がお粗末で申し訳ありませんでした。
